// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodesListing.API.Data;

#nullable disable

namespace NodesListing.API.Migrations
{
    [DbContext(typeof(NodeListingDbContext))]
    [Migration("20220712145734_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NodesListing.API.Data.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("NodesListing.API.Data.HostConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DirectoryServicePort")
                        .HasColumnType("int");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OnionServicePort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HostConfigurations");
                });

            modelBuilder.Entity("NodesListing.API.Data.Node", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HostConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Address");

                    b.HasIndex("CountryCode");

                    b.HasIndex("HostConfigurationId")
                        .IsUnique();

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("NodesListing.API.Data.Node", b =>
                {
                    b.HasOne("NodesListing.API.Data.Country", "Country")
                        .WithMany("Nodes")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NodesListing.API.Data.HostConfiguration", "HostConfiguration")
                        .WithOne("Node")
                        .HasForeignKey("NodesListing.API.Data.Node", "HostConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("HostConfiguration");
                });

            modelBuilder.Entity("NodesListing.API.Data.Country", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("NodesListing.API.Data.HostConfiguration", b =>
                {
                    b.Navigation("Node");
                });
#pragma warning restore 612, 618
        }
    }
}
